project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
website:
  navbar:
    background: "#3792ad" # Bioconductor.org blue
    left:
      - text: "Bioconductor Teaching"
        href: https://bioconductor.org/help/education-training/
      - text: "Instructors"
        href: carpentries/instructors.qmd
      - text: "Workshops"
        href: carpentries/workshops.qmd
format:
  html:
    embed-resources: false
