project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
website:
  navbar:
    logo: "images/bioconductor-logo.svg"
    logo-href: "https://bioconductor.org"
    tools:
      - icon: github
        href: https://github.com/Bioconductor/bioconductor-training
    left:
      - text: "Home"
        href: index.qmd
      - text: "Resources"
        href: resources/resources.qmd
      - text: "Carpentries"
        menu:
          - text: "Overview"
            href: carpentries/index.qmd
          - text: "Instructors"
            href: carpentries/instructors.qmd
          - text: "Workshops"
            href: carpentries/workshops.qmd
format:
  html:
    embed-resources: false
    css: styles.css
