---
title: "BachMammaryData for the intro lesson"
output: html_document
date: "`r Sys.Date()`"
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages

```{r}
suppressPackageStartupMessages({
    library(SummarizedExperiment)
    library(scRNAseq)
    library(scater)
    library(scran)
    library(tidyverse)
})
```

# Read data

```{r}
se <- BachMammaryData()
se
## check colData and rowData
head(colData(se))
table(se$Condition)
## Put in developmental order
se$Condition <- factor(se$Condition, levels = c("Nulliparous", "Gestation", "Lactation", "Post-involution"))
table(se$Sample)
se$Sample <- factor(se$Sample, levels = c("NP_1", "NP_2", "G_1",  "G_2",  "L_1",  "L_2", "PI_1", "PI_2"))
head(rowData(se))
```

# Select a subset of genes

Pull from some of those reported in [Bach et al. (2017)](https://www.nature.com/articles/s41467-017-02001-5)

```{r}
sel_genes <- c("Krt18", "Krt8", "Krt5", "Krt14", "Acta2", "Pgr", "Esr1", "Prlr","Aldh1a3", "Cd14", "Kit","Wap", "Csn2")
sel_genes <- unique(sel_genes)
length(sel_genes)
```


# Prepare data

```{r}
#Normalization

set.seed(100)
clust.se <- quickCluster(se)
se <- computeSumFactors(se, cluster=clust.se, min.mean=0.1)
se <- logNormCounts(se)
assayNames(se)

#Pull out genes of interest

se_sub <- se[rowData(se)$Symbol %in% sel_genes,]
se_sub

#Pull out logNormCounts, transpose to have samples (cells) in rows and genes in columns. Add in colData.

temp <- assay(se_sub, "logcounts") %>% as.matrix() %>% t()
colnames(temp) <- rowData(se_sub)$Symbol

rnaseq <- as.tibble(cbind(colData(se), temp))
rnaseq
```

# Serialise data

```{r}
saveRDS(rnaseq, file = "rnaseq.rds")
write_csv(rnaseq, file = "rnaseq.csv")
```

# Session info

```{r}
sessionInfo()
```
